config = {
    "version": "v1",
    "config": {
        "visState": {
            "filters": [],
            "layers": [
                {
                    "id": "a7p9yfg",
                    "type": "hexagonId",
                    "config": {
                        "dataId": "data1",
                        "label": "data1",
                        "color": [18, 147, 154],
                        "highlightColor": [252, 242, 26, 255],
                        "columns": {"hex_id": "h3_index"},
                        "isVisible": True,
                        "visConfig": {
                            "colorRange": {
                                "name": "ColorBrewer RdYlGn-6",
                                "type": "diverging",
                                "category": "ColorBrewer",
                                "colors": [
                                    "#1a9850",
                                    "#91cf60",
                                    "#d9ef8b",
                                    "#fee08b",
                                    "#fc8d59",
                                    "#d73027",
                                ],
                                "reversed": True,
                            },
                            "filled": True,
                            "opacity": 0.2,
                            "outline": False,
                            "strokeColor": None,
                            "strokeColorRange": {
                                "name": "Global Warming",
                                "type": "sequential",
                                "category": "Uber",
                                "colors": [
                                    "#5A1846",
                                    "#900C3F",
                                    "#C70039",
                                    "#E3611C",
                                    "#F1920E",
                                    "#FFC300",
                                ],
                            },
                            "strokeOpacity": 0.8,
                            "thickness": 2,
                            "coverage": 1,
                            "enable3d": False,
                            "sizeRange": [0, 500],
                            "coverageRange": [0, 1],
                            "elevationScale": 5,
                            "enableElevationZoomFactor": True,
                        },
                        "hidden": False,
                        "textLabel": [
                            {
                                "field": None,
                                "color": [255, 255, 255],
                                "size": 18,
                                "offset": [0, 0],
                                "anchor": "middle",
                                "alignment": "center",
                                "outlineWidth": 0,
                                "outlineColor": [255, 0, 0, 255],
                                "background": False,
                                "backgroundColor": [0, 0, 200, 255],
                            }
                        ],
                    },
                    "visualChannels": {
                        "colorField": {"name": "scaled", "type": "integer"},
                        "colorScale": "quantize",
                        "strokeColorField": None,
                        "strokeColorScale": "quantile",
                        "sizeField": None,
                        "sizeScale": "linear",
                        "coverageField": None,
                        "coverageScale": "linear",
                    },
                }
            ],
            "effects": [],
            "interactionConfig": {
                "tooltip": {
                    "fieldsToShow": {
                        "data1": [
                            {"name": "distance_to_shop", "format": None},
                            {"name": "distance_to_mall", "format": None},
                            {"name": "distance_to_post", "format": None},
                            {"name": "distance_to_school", "format": None},
                            {"name": "distance_to_kindergarten", "format": None},
                            {"name": "distance_to_hospital", "format": None},
                            {"name": "distance_to_police", "format": None},
                            {"name": "distance_to_station", "format": None},
                            {"name": "distance_to_railway_station", "format": None},
                            {"name": "distance_to_park", "format": None},
                            {"name": "distance_to_sport", "format": None},
                            {"name": "distance_to_restaurant", "format": None},
                            {"name": "distance_to_entertainment", "format": None},
                        ]
                    },
                    "compareMode": False,
                    "compareType": "absolute",
                    "enabled": True,
                },
                "brush": {"size": 0.5, "enabled": False},
                "geocoder": {"enabled": False},
                "coordinate": {"enabled": False},
            },
            "layerBlending": "additive",
            "overlayBlending": "normal",
            "splitMaps": [],
            "animationConfig": {"currentTime": None, "speed": 1},
            "editor": {"features": [], "visible": True},
        },
        "mapState": {
            "bearing": 0,
            "dragRotate": False,
            "latitude": 51.06487059952097,
            "longitude": 16.92781356446334,
            "pitch": 0,
            "zoom": 11.211518500962026,
            "isSplit": False,
            "isViewportSynced": True,
            "isZoomLocked": False,
            "splitMapViewports": [],
        },
        "mapStyle": {
            "styleType": "dark-matter",
            "topLayerGroups": {},
            "visibleLayerGroups": {
                "label": True,
                "road": True,
                "border": False,
                "building": True,
                "water": True,
                "land": True,
                "3d building": False,
            },
            "threeDBuildingColor": [
                15.035172933000911,
                15.035172933000911,
                15.035172933000911,
            ],
            "backgroundColor": [0, 0, 0],
            "mapStyles": {},
        },
    },
}
